// <auto-generated />
using MIP.Aws.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace MIP.Aws.Persistence.Migrations;

[DbContext(typeof(MediaIntelligenceDbContext))]
[Migration("20260617120000_DownloadMonitorBatchRun")]
partial class DownloadMonitorBatchRun
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        // Target model is defined in MediaIntelligenceDbContextModelSnapshot.
#pragma warning restore 612, 618
    }
}
