using MIP.Aws.Domain.Enums;
using MediatR;

namespace MIP.Aws.Application.Features.NewsSources;

public sealed record CreateNewsSourceCommand(
    string Name,
    string BaseUrl,
    NewsSourceType SourceType,
    ContentAcquisitionMode AcquisitionMode,
    NewsSourceAccessMode SourceAccessMode,
    bool RequiresLogin,
    string? LoginUrl,
    string? EditionUrl,
    string? LogoutUrl,
    string? PortalUsername,
    PortalLoginMethod LoginMethod,
    string? UsernameSelector,
    string? PasswordSelector,
    string? SubmitSelector,
    string? DownloadSelector,
    string? LoginSuccessSelector,
    string? SuccessUrlPattern,
    bool RequiresCaptcha,
    bool IsDownloadAllowed,
    string? Notes,
    string? DefaultLanguage,
    string? Country,
    bool RequiresAuthentication,
    bool UseHeadlessBrowser,
    int? DownloadFrequencyMinutes,
    string? ConnectorKey,
    Guid? SourceCategoryId,
    bool IsEnabled,
    string? CronExpression,
    string? ScheduleTimeZoneId,
    bool ScheduleEnabled,
    string? CredentialUsername,
    string? CredentialPassword,
    bool RequiresMfa,
    bool RequiresOtp,
    bool ManualLoginRequired,
    string? OtpInstructions,
    int? AssistedSessionTimeoutMinutes,
    PdfDiscoveryFieldsDto? PdfDiscovery = null,
    PortalAutomationFieldsDto? Portal = null) : IRequest<Guid>;
